const fs=require('fs'),path=require('path'),{chromium}=require('playwright'),XLSX=require('xlsx');
class FlowEngine{
 constructor(pm,emit){this.pm=pm;this.emit=emit;this.running=false;this.paused=false;this.stopRequested=false;this.active=new Map()}
 status(s){this.emit('status',s)}
 loadPrompts(file){const ext=path.extname(file).toLowerCase();let rows=[];if(ext==='.txt'){rows=fs.readFileSync(file,'utf8').split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(prompt=>({prompt}))}else if(ext==='.json'){rows=JSON.parse(fs.readFileSync(file,'utf8'));rows=rows.map(x=>typeof x==='string'?{prompt:x}:x)}else{const wb=XLSX.readFile(file);const sh=wb.Sheets[wb.SheetNames[0]];rows=XLSX.utils.sheet_to_json(sh);if(rows.length&&rows[0].prompt===undefined){const key=Object.keys(rows[0])[0];rows=rows.map(x=>({prompt:x[key]}))}}return rows.map((x,i)=>({id:i+1,prompt:String(x.prompt||'').trim(),status:'queued',progress:0,profile:'',file:''})).filter(x=>x.prompt)}
 async refreshProfile(id){const p=this.pm.list().find(x=>x.id===id);if(!p)throw Error('Profile not found');let browser;try{browser=await chromium.connectOverCDP(`http://127.0.0.1:${p.port}`);const ctx=browser.contexts()[0];const page=ctx.pages().find(x=>x.url().includes('flow.google.com'))||ctx.pages()[0];if(page){p.email=await page.locator('a[aria-label^="Tài khoản Google:"]').getAttribute('aria-label').then(x=>x?.replace(/^Tài khoản Google:\s*/,'')||'').catch(()=>p.email)}p.status=p.email?'ready':'login_required';this.pm.save();this.emit('profiles',this.pm.list());return p}finally{await browser?.close()}}
 async connect(p){return chromium.connectOverCDP(`http://127.0.0.1:${p.port}`)}
 async worker(profile,tasks,opts){let browser,ctx,page;try{browser=await this.connect(profile);ctx=browser.contexts()[0];page=ctx.pages().find(x=>x.url().includes('flow.google.com'))||await ctx.newPage();await page.goto('https://flow.google.com/',{waitUntil:'domcontentloaded',timeout:60000}).catch(()=>{});for(const task of tasks){while(this.paused&&!this.stopRequested)await new Promise(r=>setTimeout(r,250));if(this.stopRequested)break;await this.one(page,ctx,profile,task,opts)}}catch(e){for(const t of tasks)if(t.status==='queued'||t.status==='running'){t.status='error';t.error=e.message;this.emit('task',t)}}finally{await browser?.close()}}
 async one(page,ctx,profile,t,opts){t.status='running';t.profile=profile.email||profile.name;t.startedAt=Date.now();this.emit('task',t);try{await page.waitForSelector('div[contenteditable="true"].ProseMirror',{state:'visible',timeout:60000});const editor=page.locator('div[contenteditable="true"].ProseMirror').first();await editor.click();await page.keyboard.press('Control+A');await page.keyboard.press('Backspace');await editor.fill(t.prompt);t.progress=15;this.emit('task',t);const btn=page.locator('button[type="submit"][aria-label="Bắt đầu tạo"]').first();await btn.waitFor({state:'visible',timeout:30000});await btn.click();t.progress=25;this.emit('task',t);const file=await this.captureVideo(page,ctx,profile,t,opts);t.file=file;t.progress=100;t.status='completed';t.finishedAt=Date.now();this.emit('task',t)}catch(e){t.status='error';t.error=e.message;this.emit('task',t)}}
 async captureVideo(page,ctx,profile,t,opts){const out=path.resolve(opts.outputDir||path.join(require('electron').app.getPath('videos'),'FlowStudio'));fs.mkdirSync(out,{recursive:true});let found=null;const handler=async r=>{const h=r.headers();const ct=(h['content-type']||'').toLowerCase();if(r.status()===200&&(ct.startsWith('video/')||/\.mp4(?:\?|$)/i.test(r.url()))&&!found){found=r.url()}};page.on('response',handler);const deadline=Date.now()+(opts.renderTimeout||15*60*1000);while(Date.now()<deadline&&!this.stopRequested){await new Promise(r=>setTimeout(r,1000));if(found)break;const dl=await page.waitForEvent('download',{timeout:1000}).catch(()=>null);if(dl){const dest=path.join(out,`prompt-${String(t.id).padStart(4,'0')}.mp4`);await dl.saveAs(dest);page.off('response',handler);return dest}}page.off('response',handler);if(!found)throw Error('Chưa bắt được video response/download. Cần kiểm tra network của Flow.');const cookies=await ctx.cookies();const headers={'User-Agent':await page.evaluate(()=>navigator.userAgent)};const https=require('https');const dest=path.join(out,`prompt-${String(t.id).padStart(4,'0')}.mp4`);await new Promise((resolve,reject)=>{const req=https.get(found,{headers:{...headers,Cookie:cookies.map(c=>`${c.name}=${c.value}`).join('; ')}},res=>{if(res.statusCode<200||res.statusCode>=400)return reject(Error('HTTP '+res.statusCode));const f=fs.createWriteStream(dest);res.pipe(f);f.on('finish',()=>f.close(resolve));});req.on('error',reject)});return dest}
 async run(opts){if(this.running)return;this.running=true;this.stopRequested=false;this.paused=false;const tasks=opts.tasks||[];const profiles=this.pm.list().filter(p=>opts.profileIds?.includes(p.id)&&p.status!=='disabled');const concurrency=Math.max(1,Math.min(profiles.length,opts.concurrency||profiles.length));this.emit('queue-start',{total:tasks.length});const buckets=Array.from({length:concurrency},()=>[]);tasks.forEach((t,i)=>buckets[i%concurrency].push(t));await Promise.all(buckets.map((b,i)=>b.length?this.worker(profiles[i],b,opts):Promise.resolve()));this.running=false;this.emit('queue-finished',tasks)}
 stop(){this.stopRequested=true;this.paused=false;this.emit('status',{message:'Stopping...'})} pause(){this.paused=true;this.emit('status',{message:'Paused'})} resume(){this.paused=false;this.emit('status',{message:'Running'})}}
module.exports={FlowEngine};
